# Agregar esta sección al final de tu application.yml:

spring:
  # Configuraciones existentes...
  
  # ✅ NUEVA: Configuración de JavaMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tu-email@gmail.com}
    password: ${MAIL_PASSWORD:tu-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

# ✅ NUEVA: Configuración personalizada
unomas:
  notifications:
    email:
      enabled: true
      from: "UnoMas <noreply@unomas.com>"
      template-path: "classpath:/templates/email/"
    push:
      enabled: true
      firebase:
        # Ruta al archivo de credenciales de servicio de Firebase
        service-account-path: ${FIREBASE_SERVICE_ACCOUNT:src/main/resources/uno-mas-1f274-firebase-adminsdk-fbsvc-e26db79c2e.json}
        # Configuración del proyecto
        project-id: uno-mas-1f274